version: '3.9'
services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              gunicorn orders.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    volumes:
      - static_volume:/static

  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A orders worker --loglevel=info
    depends_on:
      - web
      - redis
    env_file:
      - ./.env.dev

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume: