version: '3.9'
services:
  web:
    container_name: orders
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A orders worker --loglevel=info
    depends_on:
      - web
      - redis
    env_file:
      - ./.env.dev

volumes:
  postgres_data: